### ISSUE TITLE
enabling ssl/tls in grpc request throwing error while running testplan

### ISSUE THREAD

**Issue by manju-v** [zalopay-oss/jmeter-grpc-request#14]
I have given cacert in system.properties javax.net.ssl.trustStore=cacert.p12
I see below error.
Response code:500
Response message:Exception: io.grpc.StatusRuntimeException: UNKNOWN: Channel Pipeline: [WriteBufferingAndExceptionHandler#0, DefaultChannelPipeline$TailContext#0].

**Comment by yanpaulo** [comment]
Hello. Have this issue been resolved? If so, what was the solution?

**Comment by huynhminhtan** [comment]
Please check PR https://github.com/zalopay-oss/jmeter-grpc-request/pull/47, hope it can be solved!

**Comment by yanpaulo** [comment]
Hello @huynhminhtan , unfortunately it doesn't. Turns out it was the lack of support for TLS NPN as the current implementation forces ALPN.
I've been able to fix it in my own fork since this one didn't accept my own branch push so that I could create a PR.
There's the fix: https://github.com/yanpaulo/jmeter-grpc-request/commit/2e681dff47dd3e51fbe25f8a3856757304c34e87

Also, how can I create a PR in this repo?

**Comment by huynhminhtan** [comment]
Hi @yanpaulo, 

It's great that you solved your problem.
Of course, you can make a merge request, why did you close it #49?

**Comment by yanpaulo** [comment]
I've created a net PR as the previous one weren't soo good. Prease review #50 .
It will solve the issue and still adds a neat feature on folder selections.

**Comment by mmahmutyilmaz** [comment]
I have being working with this plugin since last week, and I am getting this error.  Could there be another reason?

Response code:500
Response message:Exception: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
Channel Pipeline: [SslHandler#0, ProtocolNegotiators$ClientTlsHandler#0, WriteBufferingAndExceptionHandler#0, DefaultChannelPipeline$TailContext#0]

**Comment by julialoh** [comment]
Hello! I've been getting the same error as @mmahmutyilmaz. I have a pks12 file but am not sure how to pass it in metadata?

**Comment by kaaviyameena** [comment]
> I have being working with this plugin since last week, and I am getting this error. Could there be another reason?
> Response code:500 Response message:Exception: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception Channel Pipeline: [SslHandler#0, ProtocolNegotiators$ClientTlsHandler#0, WriteBufferingAndExceptionHandler#0, DefaultChannelPipeline$TailContext#0]

also facing the same issue do u have any update regarding this?
